import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import { ThemeProvider } from "@/contexts/theme-provider";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={cn("xl:w-[1050px] lg:w-[1025px] md:w-[725px] sm:w-[500px] w-full mx-auto", outfit.className)}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
